using System;
using System.Collections.Generic;

namespace AsusFanControlKimera.Localization
{
    internal static partial class Strings
    {
        private static readonly IDictionary<string, string> RussianStrings =
            new Dictionary<string, string>(StringComparer.Ordinal)
            {
                { "AlreadyRunning", "AsusFanControlKimera уже запущена." },
                { "ErrorTitle", "Ошибка Kimera" },
                { "ElevationRequired", "Требуются повышенные права.\n\n{0}" },
                { "PsExecMissingText", "Файл PsExec.exe не найден.\n\nKimera должна работать от имени SYSTEM, как run.bat в рабочей установке AsusFanControl.\n\nОжидаемый путь:\nC:\\Program Files (x86)\\AsusFanControl\\PsExec.exe" },
                { "PsExecMissingTitle", "Kimera — PsExec не найден" },
                { "LaunchSystemFailed", "Не удалось запустить Kimera от имени SYSTEM.\n\n{0}" },
                { "Options", "Параметры" },
                { "SafeLimits", "Безопасные пределы (от 40% до 99%)" },
                { "ReleaseOnExit", "Вернуть управление вентиляторами при выходе" },
                { "MinimizeToTray", "Сворачивать в область уведомлений" },
                { "StartMinimized", "Запускать свёрнутой в область уведомлений" },
                { "StartWithWindows", "Запускать с Windows (требуется подтверждение UAC)" },
                { "Debug", "Отладка" },
                { "ResetSettings", "Сбросить настройки" },
                { "Language", "Язык" },
                { "Italian", "Итальянский" },
                { "English", "Английский" },
                { "Russian", "Русский" },
                { "Help", "Справка" },
                { "About", "О программе" },
                { "ControlMode", "Режим управления" },
                { "AsusSystemDisabled", "Система ASUS (управление отключено)" },
                { "Manual", "Вручную" },
                { "TemperatureCurve", "Температурная кривая" },
                { "ManualSpeed", "Скорость вручную" },
                { "HardwareStatus", "Состояние оборудования" },
                { "CpuLabel", "ЦП:" },
                { "FansLabel", "Вент.:" },
                { "Refresh", "Обновить" },
                { "CurveHelp", "Кривая: двойной щелчок — добавить; перетащить — переместить; правый щелчок — удалить" },
                { "CurveProfile", "Профиль:" },
                { "SaveProfile", "Сохранить" },
                { "SaveProfileAs", "Сохранить как…" },
                { "RenameProfile", "Переименовать" },
                { "DeleteProfile", "Удалить" },
                { "CurrentCurve", "Текущая кривая" },
                { "Apply", "Применить" },
                { "Default", "По умолчанию" },
                { "Hysteresis", "Гистерезис °C" },
                { "Interval", "Интервал, мс" },
                { "CurveTemperatureAxis", "Температура, °C" },
                { "TrayOpen", "Открыть" },
                { "TrayAsusSystem", "Система ASUS" },
                { "TrayTemperatureCurve", "Температурная кривая" },
                { "TrayExit", "Выход" },
                { "LanguageChanged", "Язык интерфейса: русский." },
                { "EngineWaiting", "Модуль инициализирован; ожидание таблицы оборудования ASUS…" },
                { "HardwareUnavailable", "Оборудование недоступно: {0}" },
                { "HardwareInitFailedText", "Не удалось инициализировать AsusWinIO64.\n\n{0}\n\nЗапустите приложение от имени администратора и проверьте поддержку вашей модели ASUS." },
                { "HardwareUnavailableTitle", "Kimera — оборудование недоступно" },
                { "HardwareReady", "Оборудование готово. Обнаружено вентиляторов: {0}." },
                { "HardwareNotReady", "Оборудование не готово: {0}" },
                { "HardwareNotReadyText", "{0}\n\nЗакройте другие приложения управления ASUS и повторите попытку." },
                { "FansNotDetectedTitle", "Kimera — вентиляторы не обнаружены" },
                { "SystemControlReleased", "Управление возвращено системе ASUS." },
                { "CurveWaiting", "Кривая активна; ожидание температуры." },
                { "ManualStatus", "Ручной режим: ШИМ {0}%." },
                { "CommandSent", "{0} Команда отправлена вентиляторам ({1}); значение {2}/255." },
                { "TraySystem", "Kimera — система ASUS" },
                { "FanControlError", "Ошибка управления вентиляторами: {0}" },
                { "ZeroRpmReason", "Один из вентиляторов показал 0 об/мин три раза подряд." },
                { "InvalidTemperatureStatus", "Недопустимая температура ASUS ({0} °C), попытка {1}/2: кривая приостановлена." },
                { "InvalidTemperatureReason", "Датчик ASUS дважды подряд вернул недопустимую температуру." },
                { "CurveStatus", "Кривая: {0} °C → ШИМ {1}%." },
                { "HardwareReadError", "Ошибка чтения оборудования ({0}/3): {1}" },
                { "HardwareReadReason", "Три последовательные попытки чтения оборудования завершились ошибкой." },
                { "InvalidCurveTitle", "Недопустимая кривая" },
                { "SaveProfileAsTitle", "Сохранить профиль кривой" },
                { "RenameProfileTitle", "Переименовать профиль кривой" },
                { "ProfileNamePrompt", "Имя профиля:" },
                { "InvalidProfileName", "Введите непустое имя длиной не более {0} символов." },
                { "InvalidProfileTitle", "Недопустимое имя профиля" },
                { "DuplicateProfileName", "Профиль с именем «{0}» уже существует." },
                { "DeleteProfilePrompt", "Удалить профиль «{0}»? Текущая кривая не изменится." },
                { "DeleteProfileTitle", "Удалить профиль кривой" },
                { "UnsavedCurrentCurvePrompt", "Текущая кривая не сохранена в профиле. Сохранить её перед загрузкой выбранного профиля?" },
                { "UnsavedProfilePrompt", "В профиле «{0}» есть несохранённые изменения. Сохранить их перед переключением?" },
                { "UnsavedProfileTitle", "Изменения профиля" },
                { "ProfileSavedStatus", "Профиль кривой «{0}» сохранён." },
                { "ProfileDeletedStatus", "Профиль кривой «{0}» удалён; текущая кривая остаётся активной." },
                { "OK", "ОК" },
                { "Cancel", "Отмена" },
                { "UnsafeLimitsText", "Если отключить безопасные пределы, скорость вентиляторов можно будет снизить до 1%. Слишком низкое значение может физически остановить вентилятор.\n\nПродолжить?" },
                { "UnsafeLimitsTitle", "Kimera — потенциально опасная настройка" },
                { "ReleaseDisabledText", "Если отключить эту опцию, при обычном выходе из Kimera управление вентиляторами не вернётся прошивке ASUS. Последний тестовый режим и значение ШИМ могут остаться активными после выхода.\n\nПродолжить?" },
                { "ReleaseDisabledTitle", "Kimera — управление вентиляторами после выхода" },
                { "InteractiveProfileUnavailable", "Профиль активного пользователя недоступен." },
                { "StartupChangeFailed", "Не удалось изменить автозапуск:\n{0}" },
                { "DebugEnabled", "Отладка включена: {0}" },
                { "DebugDisabled", "Отладка отключена." },
                { "ResetPrompt", "Сбросить все настройки?" },
                { "AboutText", "Asus Fan Control Kimera\nВерсия {0}\n\nМодуль совместим с AsusFanControl.\nИнтерфейс и управление кривой реализованы заново." },
                { "FailSafeReleasedStatus", "АВАРИЙНЫЙ РЕЖИМ: управление возвращено прошивке ASUS. {0}" },
                { "FailSafeUnconfirmedStatus", "АВАРИЙНЫЙ РЕЖИМ: возврат управления прошивке не подтверждён. {0}" },
                { "Snapshot", "температура={0} °C; {1}; ШИМ={2}%; значение={3}/255" },
                { "UnexpectedError", "Непредвиденная ошибка: {0}" },
                { "FailSafeTitle", "Kimera — активирован аварийный режим" },
                { "FailSafeReleased", "Управление возвращено прошивке ASUS" },
                { "FailSafeUnconfirmed", "ВНИМАНИЕ: возврат управления прошивке не подтверждён" },
                { "FailSafeDetails", "Время: {0:yyyy-MM-dd HH:mm:ss}\r\n\r\nПричина: {1}\r\n\r\nЗатронутые вентиляторы: {2}\r\n\r\nПоследние значения: {3}\r\n\r\nВозврат управления прошивке: {4}" },
                { "Succeeded", "ВЫПОЛНЕНО" },
                { "NotConfirmed", "НЕ ПОДТВЕРЖДЕНО" },
                { "Acknowledge", "Понятно" },
                { "OpenLog", "Открыть журнал" },
                { "OpenLogFailed", "Не удалось открыть журнал" },
                { "CurveEmpty", "Кривая не может быть пустой." },
                { "CurveFormat", "Неверный формат кривой. Используйте пары температура,процент, разделённые дефисами." },
                { "CurveTemperatureRange", "Температура должна быть в диапазоне от 20 до 105 °C." },
                { "CurveSpeedRange", "Скорость должна быть в диапазоне от 1 до 100%." },
                { "CurveMinimumPoints", "Кривая должна содержать не менее двух точек." },
                { "CurveDuplicateTemperature", "Каждое значение температуры может встречаться только один раз." },
                { "CurveDecreasingSpeed", "Скорость не должна уменьшаться при росте температуры." },
                { "DriverFanCount", "Драйвер ASUS не вернул допустимое число вентиляторов (1–8) после 20 попыток." }
            };
    }
}
